# Generated by Django 4.0.3 on 2022-04-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compant_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holidays',
            new_name='Holiday',
        ),
    ]
