# Generated by Django 4.0.3 on 2022-03-31 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('c_type', models.IntegerField()),
                ('remarks', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
