# Generated by Django 4.0.3 on 2022-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('c_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('day', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default=0, max_length=25)),
                ('remarks', models.TextField(default='')),
            ],
        ),
    ]
