# Generated by Django 4.0.3 on 2022-04-20 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('c_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('day', models.DateField(default=datetime.date.today)),
                ('remarks', models.TextField(default='')),
            ],
        ),
    ]
