# Generated by Django 4.0.3 on 2022-03-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='remarks',
        ),
        migrations.AddField(
            model_name='dailylogs',
            name='day',
            field=models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='dailylogs',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
