# Generated by Django 4.0.3 on 2022-04-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
