# Generated by Django 4.0.3 on 2022-04-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='day',
        ),
    ]
