# Generated by Django 4.0.3 on 2022-04-17 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailylog_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 8, 8, 36, 274602, tzinfo=utc)),
        ),
    ]
