# Generated by Django 4.0.3 on 2022-04-08 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffleave',
            unique_together={('date', 'user')},
        ),
    ]
