# Generated by Django 4.0.3 on 2022-04-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.department'),
        ),
    ]
