# Generated by Django 4.0.3 on 2022-04-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_departments_department_rename_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.department'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='user.role'),
        ),
    ]
