# Generated by Django 4.0.3 on 2022-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
