# Generated by Django 4.0.3 on 2022-04-22 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='day',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
