# Generated by Django 4.0.3 on 2022-04-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
